services:
  voice-magic:
    build:
      context: .
      dockerfile: Dockerfile.aliyun
    image: voice-magic:aliyun
    container_name: voice-magic
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - voice_magic_data:/app/data
      - voice_magic_previews:/app/previews
    restart: always

volumes:
  voice_magic_data:
  voice_magic_previews:
